### ISSUE TITLE
apply ci/cd

### ISSUE THREAD

**Issue by hobiJeong** [modern-agile-team/dongurami-server-v2#12]
### Summary

git actions과 Docker를 통해 ci/cd pipeline을 구축 했습니다.

### GitHub Actions
workflow를 사용해서 Docker Image를 빌드하고 Hub에 Push합니다.(이 때 env파일을 GitHub Actions secrets를 통해 생성합니다.) ec2에서 image를 pull하고 컨테이너를 실행합니다.

### dockerfile
dockerfile에서 배포(서버 실행)에 필요한 파일들만 build 합니다.

### docker-compose.yml
docker-compose에 작성된 내용을 토대로 컨테이너를 실행합니다.

### Related Issue Link

#1

**Comment by rrgks6221** [comment]
이슈 본문에 PR 에 올라갈 workflows, dockerfile 같은 본문은 없어도 될듯해요
